services:
  app:
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "6060:80"
    environment:
      TZ: "Asia/Tokyo"

  db:
    image: mysql:latest
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql
    environment:
      MYSQL_DATABASE: hr
      MYSQL_USER: hr
      MYSQL_PASSWORD: hrhrhrhr
      MYSQL_ROOT_PASSWORD: hrhrhrhr
      TZ: 'Asia/Tokyo'

  php-my-admin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "6061:80"
    environment:
      MYSQL_USERNAME: hr
      MYSQL_ROOT_PASSWORD: hrhrhrhr
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db-store:
